discord-webhook: https://discordapp.com/api/webhooks/370959388963241984/1tuO6VvxB_Kg0Nzhx0UshDwNrNF9KZOFb7Yv-b7EWuJR1bTEre9c9cC8uMHoq8z-0JCv
discord-json: https://discordapp.com/api/guilds/364823341506363392/widget.json

sw-json: https://api.steampowered.com/ISteamRemoteStorage/GetPublishedFileDetails/v1/
sw-json-file-id: 723217262

colors:
  pending: 15588927        # #EDDE3F
  passed: 3779158          # #39AA56
  fixed: 3779158           # #39AA56
  broken: 14370117         # #DB4545
  failed: 14370117         # #DB4545
  still failing: 14370117  # #DB4545
  canceled: 10329501       # #9D9D9D
